# this workflow is used to test the e2e happy path of the signpath/github-action-submit-signing-request action
name: e2e happy path tests

on:
    workflow_dispatch:
      inputs:
        environment:
          required: true
          type: string
        workflow-dispatch-event-id:
          required: true
          type: string
jobs:
  call-base-workflows:
    uses: ./.github/workflows/e2e-workflow-base.yml
    secrets:
      SIGNPATH_API_TOKEN: ${{ secrets.SIGNPATH_API_TOKEN }}
      SIGNPATH_TOKEN_ENCRYPTION_KEY: ${{ secrets.SIGNPATH_TOKEN_ENCRYPTION_KEY }}
    with:
      workflow-dispatch-event-id: ${{ inputs.workflow-dispatch-event-id }}
      environment: ${{ inputs.environment }}
  build:
    runs-on: windows-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upload the artifcat file
        id: upload-artifact-step
        uses: actions/upload-artifact@v4
        with: 
          name: original-artifact
          path: ./artifacts/small.exe
      - name: Run submit signing request
        id: submit_with_download
        uses: signpath/github-action-submit-signing-request@main
        with:
            connector-url: ${{ vars.CONNECTOR_URL }}
            api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
            organization-id: ${{ vars.ORGANIZATION_ID }}
            project-slug: e2e-gha-test-project
            # this SigningPolicy has auto-approve enabled, so you don't need to approve the signing request
            signing-policy-slug: e2e-test-sp
            artifact-configuration-slug: exe-in-zip
            github-artifact-id: '${{ steps.upload-artifact-step.outputs.artifact-id }}'
            wait-for-completion: true
            output-artifact-directory: signed-artifact
            parameters: |
              param1: ${{ toJSON('value1') }}
              param2: "value2"
      - name: Upload the signed artifact
        id: upload-signed-artifact-step
        uses: actions/upload-artifact@v4
        with: 
            name: signed-artifact
            path: signed-artifact
      - run: |
          echo "Signed Artifact Id: ${{ steps.upload-signed-artifact-step.outputs.artifact-id }}"
